### ISSUE TITLE
enahnce api for deps resolving

### ISSUE THREAD

**Issue by judovana** [mkoncek/classpathless-compiler#15]
eg List<String> getDeps(IdentifiedSource.. inputs)
eg List<String> getDeps(IdentifiedBytecode.. inputs)

not sure if possible at all...

**Comment by mkoncek** [comment]
Part of this is already present in -utils module.
1) getDeps from sources is more complex than it looks
* parsing explicit imports is relatively simple
* for `import a.b.*;` you would already need to have a classpath
* you need to know what is present in `java.lang` package
* you need to know what is present in the package of the source you are compiling
* you need to know what is present in the default package
* you need to know the names of outer classes from each context of usage (names of outer classes can also be used without full qualification)
* in case of name conflicts you need to read JLS and resolve them in correct order

2) getDeps from bytecode: This is obtaainable but not in a single method call. If you want all the dependencies for a compilation task you need to:
* obtain the set of outer/nested classes of you current class by calling `BytecodeExtractor.extractFullGroup`
* obtain the set of direct imports of *all* your outer/nested classes by calling `BytecodeExtractor.extractTypenames` on all the entires of your previous set.
* obtain the full nested groups of all the previous direct imports again by calling `BytecodeExtractor.extractFullGroup`

see: https://github.com/mkoncek/classpathless-compiler/blob/5ef17c049184a14aaac881e9de7f8d61fb79abe4/impl/src/main/java/io/github/mkoncek/classpathless/impl/CompilerJavac.java#L164:L194

**Comment by judovana** [comment]
yah. Dropping that sourrce case for sure. The idea was, that actually the compiler will compile m and then read it from binary. That can be impelemented with currenty toolchain in two steps. so clisng case sourcse:)

as from bin, Can you unite it in one method?

**Comment by mkoncek** [comment]
See if you can work with it.

**Comment by judovana** [comment]
public static Collection<String> extractDependenciesPrivateImpl(Collection<String> result

should be private, or at least package private, even if it have to go through some protected overhead.

**Comment by mkoncek** [comment]
Issue addressed

**Comment by judovana** [comment]
Call to depsResovler added to cli: https://github.com/pmikova/java-runtime-decompiler/pull/218/commits/b79c02f8ba8224c3e18a4248c833726adaf0155a

Btw - as it is using the ClassesProvider, shouldnt it use also the MessagesListener and follow thi  io.org.cpcl properties?

An idea - is it possible - and reasonable -  , instead of flat list, provide map, so the chain is visible?
Not sure how usefull it is, but each class I tried have surprising amount of deps....

**Comment by mkoncek** [comment]
1) Yes, I can add an overload (already doing the same thing in CPLC -impl).
2) You mean the returned type? That is very easy since:
`var result = new TreeSet<String>();`
My question is, what is your use case? Are you looking for anything particular in the result? I thought the returned collection is simply mered with another one... I can return `Set` or `SortedSet`. The implementation detail is quite important and I will definitely keep using it instead of any other collection.

**Comment by mkoncek** [comment]
Logging is a different problem, I really don't want to bring logging logic into utilities. Easiest I can do is to log everything with particular level.

**Comment by mkoncek** [comment]
See:
https://github.com/mkoncek/classpathless-compiler/commit/85dc852f3f1931830bdbb9b5d5d713526f4c0f97
https://github.com/mkoncek/classpathless-compiler/commit/ca982bfc3a6474f75279ee380d47e4a66b96b85c

**Comment by judovana** [comment]
Thanx for the logging. It may be enough.

Not set, map of maps:). But as I'm saying - it may be nonsense. 
The map would be:
key:someClass1, values: dependence1,depndence2, dependece3
key:someClass1$1, values: dependence1,depndence2, dependece3
key:someClass1$2, values: dependence1,depndence2, dependece3
...
key:someClass1$namedInner, values: dependence1,depndence2, dependece3
key:someClass1$anotherNamedInner, values: dependence1,depndence2, dependece3
....
Where maybe the someClass1$numbers and someClass2$nameds may be another leaves under someclass1.

Now correct me, but
key:someClass2
key:someClass3

May NOT appear, or can they?

**Comment by mkoncek** [comment]
To answer your question: No **in the current implementation**.
I can do what you want at the cost of more complex implementation on my side. See if you can work with `extractDependencies2` from this commit: https://github.com/mkoncek/classpathless-compiler/commit/6cac194ab181d5840759534f921cdcce332e741f

If you really do want a version as used there, I will provide it under some more appropriate name.

**Comment by judovana** [comment]
no need. It was just idea. Whch was brougt up by surprising amount of dependencies in the listing.
