### ISSUE TITLE
Shall we drop pre/postprocessors?

### ISSUE THREAD

**Issue by mkoncek** [mkoncek/classpathless-compiler#16]
@judovana 
I think there are better ways of handling possible issues this was intended to solve.
I believe this would introduce unnecessary complexity.
Moreover we don't currently have a use case for any of it.

To remind you:
* Preprocessors were intended to obtain source code and slightly modify it using automatic rules. Like transforming dots to dollars, but I don't think this can be done in a simple and safe way.
* Postprocessors were intended to modify source code based on compiler error messages (there was a case of what I believed was missing `abstract` keyword, but I am not sure of it anymore).

**Comment by judovana** [comment]
I think they still have a place.
Eg in jasm, two rendnant keywordsa re printed, and can be remvoed and so on.
But msot likely this feature should benimplemented in jrd like popupmenu in source view, with item of "fix common issues"
 - the jasm keywords
 -  cfr inner classes naming and so on.

quite a work at the end it wil be

**Comment by judovana** [comment]
so ok from dropping from cplc. They need user to much
