### ISSUE TITLE
extract io.github.mkoncek.cplc.log-to-provider to public static constant

### ISSUE THREAD

**Issue by judovana** [mkoncek/classpathless-compiler#17]
... so it can be reused, instead written again.
The io.github.mkoncek.cplc.log-to-provider also should have levels, or enumeration
eg io.github.mkoncek.cplc.log-to-provider=1 ... io.github.mkoncek.cplc.log-to-provider-5
or io.github.mkoncek.cplc.log-to-provider=ALL .. io.github.mkoncek.cplc.log-to-provider=IGNORES,PROVIDES
and so

becasue really spamming out with 10^6 of ignored lambdas really is not making any help.
Simple 
```
if (s.startsWith("Ignoring")){
  return;
}
```
Made the log moreover useful.

Maybe not dot log The ```Ignoring lambda...``` line?

**Comment by judovana** [comment]
hmhhm.. yah, skipping over  is also pretty verbose...  so enumeration would be a choice. But maybe better can be to handle it in gui.
Right, it can OOM :)

**Comment by judovana** [comment]
See https://github.com/pmikova/java-runtime-decompiler/pull/218/commits/367ee70c61c9d6d0e9ba2cb4788a3fe2643f93dd#diff-81017fc8496494ba6c25886be4423f7982556684cc29d611e2307ce6a4facc34 for inspiration.

I had split the most verbose ones to be enabled by separate values:
```
    public static final String CPLC_DUPLICATED_CODE_VERBOSITY_CONSTANT = "io.github.mkoncek.cplc.log-to-provider";
    public static final String CPLC_IL = "IGNORE_LAMBDAS";
    public static final String CPLC_IA = "IGNORE_ARRAYS";
    public static final String CPLC_SO = "SKIPPING_OVER";
    public static final String CPLC_AC = "ADDING_CLASS";
    public static final String CPLC_R = "INTERESTING";
```

**Comment by mkoncek** [comment]
I see... that is one way to solve it...
Related: https://github.com/pmikova/java-runtime-decompiler/issues/220

Thinking about it: currently our logging uses severity level from `java.util.logging`. In retrospective, I don't think this reflects its true usage. I think it would be more reasonable to use some sort of `Category` (like you just made up) instead of severity `Level`. Whenever I added logging code I had to think how "severe" the message was and it is hard to say for sure. With `Category` it would be mush more clear.

A slight problem is that this would break CPLC API but I am in favor of this.
I could create an enum class `Category` listing for example messages like: lambdas, arrays, skipping, bytecode extraction...

**Comment by judovana** [comment]
I have currently no strong opinion, as the filtering I added is enough. But is hackish.
If you are in favor, then the Cathegory sounds like best to do.

As for the api, you canm al;ways make it backward compatible by having the current method simply calling the warhorse with all or nothing from the cathegory, and  second method calling the warhorse with the user specified set.

**Comment by mkoncek** [comment]
I was able to categorize and comment on various types of log messages, see:
https://github.com/mkoncek/classpathless-compiler/commit/a17bb099c8bab4377d12b687f9fc77161c81b77d
https://github.com/mkoncek/classpathless-compiler/commit/9a5cff0cde9c0b3b54a558c55f07d5d6f62189c2

I am not sure whether the enum should be a standalone class or a nested class of `MessagesListener`.
I would need to create some mapping of severity to sets of categories but i have a rough idea:
ALL -> OOM :(
FINE -> ignore the most useless and spammy messages which make ~80% of the output (ignoring... / skipping..., not sure about loading...)
CONFIG (or something similar) -> keep only non-spammy messages (so keep things like bytecode extraction, file objects opened by the compiler, compilation results and so)

In any case there are still categories prefixed with `COMPILER_`, these kinds you probably want in any case.

**Comment by judovana** [comment]
Nested or not does not meter.   I think you get paranoid from the cplc implementation :)
I think the mapping is moreover redundant. This logging moved out of the standard ways since origin., and double when the -Dcplc...logging proeprty was introduced (thanxx for it).

I'm missing the set up of the enum. Up to now, those were enabled by the property. Right now tey are enabled by?
You did not liked the idea of the fields of enums, passes as values of -Dcplc...loging?
What I see is alignerment by the some mapping. I would reallya void that, and rather go by the apporach I suggested - to have an array, containig subset of that enum, whcih is actually telling, what to log.
And this array is read from the property. By default, if the proeprty is on and without content - it would be all.

As you did  - it is very confusing. The enum and the cathegorization of the messages is briliant, but the control is terrible.

**Comment by mkoncek** [comment]
@judovana Shall we close this?

**Comment by judovana** [comment]
yah.
